repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: pdm run black
        language: system
        types: [python]

      - id: ruff
        name: ruff
        entry: pdm run ruff check . --fix
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: pdm run mypy src tests
        language: system
        types: [python]

      - id: unit-tests
        name: unit-tests
        entry: pdm run pytest tests/unit
        language: system
        types: [python]
